version: '3'

services:

  nginx:
    container_name: nginx
    build: docker/nginx
    links:
      - php
    ports:
      - 8001:80
    working_dir: /application
    volumes:
      - ./:/application

  php:
    container_name: php
    build: docker/php
    links:
      - postgres
      - redis
    environment:
      CORE_EXT_CONFIGURATION_ENV: development
      XDEBUG_IDEKEY: xdebug
      XDEBUG_REMOTE_HOST: 127.0.0.1
      XDEBUG_REMOTE_PORT: 9000
      XDEBUG_REMOTE_ENABLE: 1

    working_dir: /application
    volumes:
      - ./:/application

  composer:
    container_name: composer
    image: composer
    command: install
    working_dir: /application
    volumes:
      - ./:/application

  postgres:
    container_name: postgres
    image: postgres:9.5
    environment:
      POSTGRES_USER: ieducar
      POSTGRES_PASSWORD: ieducar
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    restart: always
